
def Giant_Cockroach():
    return{
        "Name":"Giant_Cockroach",
        "Hp":200,
        "Max_Hp":200,
        "PhysicalAtk":100,
        "PhysicalFlatPen":5,
        "PhysicalPercentPen":1,
        "PhysicalArmore":70,
        "MagicAtk":0,
        "MagicFlatPen":0,
        "MagicPercentPen":0,
        "MagicArmore":30,
        "Mana":200,
        "Max_Mana":200,
        "Speed":65,
        "Crit_Rate":0,
        "Crit_Dmg":50,
        "Moves":{
            "Bite":{
                "PhysicalMultiplier":0.8,
                "Weight":30
            },
            "Jump":{
                "Weight":10,
                "In_Air":True,
            },
            "Jump_Attack":{
                "PhysicalMultiplier":2,
                "Weight":0
            }
        }
    }


def Wounded_Scout():
    return{
        "Name":"Wounded_Scout",
        "Hp":250,
        "Max_Hp":195,
        "PhysicalAtk":105,
        "PhysicalFlatPen":45,
        "PhysicalPercentPen":11,
        "PhysicalArmore":50,
        "MagicAtk":0,
        "MagicFlatPen":0,
        "MagicPercentPen":0,
        "MagicArmore":30,
        "Mana":75,
        "Max_Mana":200,
        "Speed":60,
        "Crit_Rate":2,
        "Crit_Dmg":50
    }
def Armored_Knight():
    return{
        "Name":"Armored_Knight",
        "Hp":600,
        "Max_Hp":600,
        "PhysicalAtk":105,
        "PhysicalFlatPen":40,
        "PhysicalPercentPen":10,
        "PhysicalArmore":300,
        "MagicAtk":0,
        "MagicFlatPen":0,
        "MagicPercentPen":0,
        "MagicArmore":35,
        "Mana":200,
        "Max_Mana":200,
        "Speed":20,
        "Crit_Rate":10,
        "Crit_Dmg":50
    }
def Mage():
    return{
        "Name":"Mage",
        "Hp":300,
        "Max_Hp":300,
        "PhysicalAtk":0,
        "PhysicalFlatPen":0,
        "PhysicalPercentPen":0,
        "PhysicalArmore":50,
        "MagicAtk":200,
        "MagicFlatPen":50,
        "MagicPercentPen":15,
        "MagicArmore":150,
        "Mana":200,
        "Max_Mana":200,
        "Speed":50,
        "Crit_Rate":12,
        "Crit_Dmg":55
    }
def Magicaly_Enhanced_Orc():
    return{
        "Name":"Magicaly_Enhanced_Orc",
        "Hp":600,
        "Max_Hp":600,
        "PhysicalAtk":200,
        "PhysicalFlatPen":10,
        "PhysicalPercentPen":7,
        "PhysicalArmore":100,
        "MagicAtk":0,
        "MagicFlatPen":0,
        "MagicPercentPen":0,
        "MagicArmore":300,
        "Mana":200,
        "Max_Mana":200,
        "Speed":55,
        "Crit_Rate":5,
        "Crit_Dmg":68
    }
def Corrupted_Lord():
    return{
        "Name":"Corrupted_Lord",
        "Hp":700,
        "Max_Hp":700,
        "PhysicalAtk":150,
        "PhysicalFlatPen":25,
        "PhysicalPercentPen":10,
        "PhysicalArmore":250,
        "MagicAtk":175,
        "MagicFlatPen":50,
        "MagicPercentPen":8,
        "MagicArmore":300,
        "Mana":300,
        "Max_Mana":300,
        "Speed":75,
        "Crit_Rate":10,
        "Crit_Dmg":60
    }
